### ISSUE TITLE
Development of `user-service`

### ISSUE THREAD

**Issue by overparser** [overparser/anki-gpt-repeater#5]
# Development of `user-service`

## Tasks

- [ ] **Create OpenAPI specification**:
  - [ ] Define endpoints, request, and response models.
  - [ ] Add example data.
  - [ ] Document error codes.

- [ ] **Generate server code**:
  - [ ] Use OpenAPI Generator to create the base code.
  - [ ] Validate the generated code (data structures, routes).

- [ ] **Implement business logic**:
  - [ ] Set up the MongoDB connection.
  - [ ] Implement CRUD operations.
  - [ ] Add input validation.

- [ ] **Configure settings**:
  - [ ] Use a `.env` file for sensitive data.
  - [ ] Implement configuration handling using Pydantic.

- [ ] **Add auxiliary features**:
  - [ ] Implement a health-check endpoint (`/health`).
  - [ ] Add logging (e.g., using `structlog`).
